### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Alex4S** [Alex4S/reddit-front-page-posts#17]
- [x] Add styled-components
- [x] Add next-redux-wrapper
- [x] Refactoring store
- [x]  Add axios
- [x] Add humps, moment, redux-thunk
- [x]  Rename utils dir to util 
- [x] Add normalizePosts utility
- [x] Add callApi utility
- [x] Add Flat colors
- [x]  Add scripts to package.json
- [x]  Add the main page (page/index.js)
- [x]  Add the default page view (page/_document.js)
- [x]  Add Caching

**Thumbnail component:**
- [x] Add Thumbnail component
- [x] Add Stories to Thumbnail component
- [x] Add Tests to Thumbnail component

**Score component:**
- [x] Add Score component
- [x] Add Stories to Score component
- [x] Add Tests to Score component

**Post component:**
- [x] Add Post component
- [x] Add Stories to Post component
- [x] Add Tests to Post component

**Heading component:**
- [x] Add Heading component
- [x] Add Stories to Heading component
- [x] Add Tests to Heading component

**PostsList component:**
- [x] Add PostsList component
- [ ] Add Stories to PostsList component
- [ ] Add Tests to PostsList component
- [x] Add PostsList actions
- [x] Add PostsList reducer
- [x] Add PostsList sagas
- [x] Add PostsList selectors
- [x] Add Tests to PostsList actions
- [x] Add Tests to PostsList reducer
- [x] Add Tests to PostsList sagas
- [x] Add Tests to PostsList selectors
